### ISSUE TITLE
#1 - Unhappy path

### ISSUE THREAD

**Issue by Marcosreuquen** [MatiToledo/ppt-online#1]
Buenas, Mati! 

Ante todo, felicitaciones por llegar hasta acá. Realmente el funcionamiento está genial y el maquetado está increíble, me encantó como quedó. 
El issue hace referencia a cuando uno no sigue el happy path. O sea, si uno o ambos jugadores no eligen antes de que se termine el tiempo, la web continúa a resultados con la elección previa. Podrías agregarle ahí un control previo en el que si cuando terminó el tiempo no eligió al menos uno de los dos, vuelva a alguna page previa. 

Saludos!

**Comment by MatiToledo** [comment]
Buenass, sí anoche me di cuenta de eso (mi mente estos días solo pensaba en el desafíos jeje) e iba a hacer algo para que se reinicie la elección cuando apretas volver a jugar pero me re colgué. Muchas gracias por el resto !!
