### ISSUE TITLE
#2 - 401 (Unauthorized) en page /waiting

### ISSUE THREAD

**Issue by Marcosreuquen** [MatiToledo/ppt-online#2]
Buenas, Mati! 

Al dar 'Jugar' en la page `/waiting` me sale un error 401 en un requests y se queda ahí. 
Te lo pego acá para que lo puedas ver.

![image](https://user-images.githubusercontent.com/75027556/136315160-1069b0b5-6f4d-410d-b03e-6d5d42fcd744.png)

Pareciera ser un tema con las promesas o de validaciónd e datos en la API, porque responde "No existís".
![image](https://user-images.githubusercontent.com/75027556/136315533-854714a7-964f-436d-b961-720e81cc6371.png)

Saludos!

**Comment by MatiToledo** [comment]
Mmm raro, ese es el res a la hora de crear la room si es que no existe ningún usuario con ese userId, ahí lo controlo porque hoy testeando no me salto nada. Y ahora probándolo en mi pc no me salta ningún error, se que no debería ser la manera, pero probaste reseteando el local-storage ? jeje

**Comment by Marcosreuquen** [comment]
Ahí probé con eso y me pasó lo mismo. Capaz quedó algo sin commitear.

**Comment by MatiToledo** [comment]
Uuuh que sad, ahora ya apague todo encima, pero mañana me fijo bien qué onda porque no toque nada de eso para arreglar lo otro, pero si toque algo en el historial de los commit debería figurarme, pero bueno mañana lo arreglo así ya queda
